### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danielleodean**
based on discussion in team meeting on standards

### CODE REVIEW

**Comment by danielleodean** [comment]
The only section that was discussed that hasn't been added is a "Cleaning Up" section after the "Steps" section - @jiata can you add that?

**Comment by jiata** [comment]
LGTM, will add clean up section in a separate PR @danielleodean

**Comment by grecoe** [comment]
Looking at master, the README is still missing the Cleaning Up section. As discussed, even if there is nothing to do, the section should still be there. I'm assuming cleanup will occur if they follow all the steps? Just mention that.

**Comment by danielleodean** [comment]
Right, I mentioned that above and JS said he'll take care of it in another PR (as I did the other section headers based on what he already had there). Thanks

**Comment by grecoe** [comment]
Yes, I missed the separate PR, so, never mind.

**Pull request merged**
